services:
  wvn_nvidia:
    extends:
      file: docker-compose-gui.yaml
      service: wvn
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    dns:
      - 133.26.136.30
    networks:
      default:
      devcontainer_ros_net:
        aliases:
          - ros1-wvn

networks:
  devcontainer_ros_net:
    external: true
